In [1]:
import numpy as np
print(np.__version__)


1.20.3


In [2]:
a=np.array(10)
print(a)

10


In [3]:
a=np.array([10,20,30])
print(a)

[10 20 30]


In [5]:
a=np.array([[10,20],[30,40]])
print(a)
print(a[1][0])

[[10 20]
 [30 40]]
30


In [7]:
a=np.array([[[10,20,30],[30,40,60]],[[80,90,100],[10,110,40]]])
print(a)
print(a[1][0])

[[[ 10  20  30]
  [ 30  40  60]]

 [[ 80  90 100]
  [ 10 110  40]]]
[ 80  90 100]


In [15]:
l=[[10,20],[30,40]]
a=np.asarray(l,dtype=int,order="F")
print(a)

for i in np.nditer(a):
    print(i)
    
a=np.asarray(l,dtype=int,order="C")
print(a)

for i in np.nditer(a):
    print(i)

[[10 20]
 [30 40]]
10
30
20
40
[[10 20]
 [30 40]]
10
20
30
40


In [19]:
s=b"Welcome to numpy"
b=np.frombuffer(s,dtype='S1',count=5,offset=6)
print(b)

[b'e' b' ' b't' b'o' b' ']


In [21]:
l=[10,20,30]
b=np.fromiter(l,dtype=int)
print(b)

[10 20 30]


In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
np.full(3,2)

array([2, 2, 2])

In [26]:
np.full([2,3],2)

array([[2, 2, 2],
       [2, 2, 2]])

In [27]:
np.full([3,3,4],10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [28]:
np.random.rand(1)

array([0.20939303])

In [29]:
np.random.rand(2,3)

array([[0.3420482 , 0.60901193, 0.76312069],
       [0.95570243, 0.20845188, 0.05300703]])

In [30]:
np.random.rand(2,3,3)

array([[[0.95058052, 0.51929458, 0.25566953],
        [0.03684431, 0.1313494 , 0.69569447],
        [0.33658812, 0.0375275 , 0.63322533]],

       [[0.502929  , 0.02897048, 0.28217197],
        [0.37289081, 0.57205165, 0.1235661 ],
        [0.3639112 , 0.57715568, 0.40089583]]])

In [33]:
np.ones([1,3])

array([[1., 1., 1.]])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])